config/routes.rb
Rails.application.routes.draw do
  get 'carts/show'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'homes#index'
  resources :products
  resources :order_details
  resource :carts, only:[:show]
  resource :orders, only:[:show]
  post '/button', to: 'orders#update_cart_status'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :user
    has_many :order_details
    after_initialize :set_order_date
    before_save :set_total
    enum status: {pending: 0, placed: 1, delivered: 2}

    
    def total 
        order_details.collect{|order_detail| order_detail.valid? ? order_detail.sub_total : 0}.sum
    end

    def set_total
        self[:total_amount] = total
    end

    private def set_order_date
        self[:order_date] = Date.today
    end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
    belongs_to :product
    belongs_to :order
    before_save :set_unit_price
    before_save :set_sub_total

    def unit_price
        if persisted?
            self[:unit_price]
        else
            product.price
        end
    end

    private def set_unit_price
        self[:unit_price] = unit_price
    end

    def sub_total
        unit_price * quantity
    end

    private def set_sub_total
        self[:sub_total] = sub_total
    end
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :product_category
    has_many :order_details
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
    has_many :products
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :orders
  validates_presence_of :first_name, :last_name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include ApplicationHelper
  before_action :configure_permitted_parameters, if: :devise_controller?

    protected

        def configure_permitted_parameters
            devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
            devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :is_admin])
        end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @order_details = current_order.order_details
    if @order_details.size == 0
      @body = 'Your cart is empty'
    else 
      @body = ''
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
    def index
    end
end

app/controllers/order_details_controller.rb
class OrderDetailsController < ApplicationController
    def create
        @order = current_order
        @order.user_id = current_user.id
        @product_id = params[:order_detail][:product_id].to_i
        @quantity = params[:order_detail][:quantity].to_i
        @is_detail_present = @order.order_details.find_by(product_id: @product_id)

        if !current_user.is_cart_empty && @is_detail_present!=nil            
           @order_detail = @order.order_details.find_by(product_id: @product_id)
           @order_detail.quantity += @quantity
           @order_detail.save!
        else    
            @order_details = @order.order_details.new(order_params)
            current_user.is_cart_empty = false
            current_user.save!
        end  
        @order.save!
        session[:order_id] = @order.id
    end

    def new
    end

    def update
        @order = current_order
        @order_detail_id = params[:id].to_i
        @order_detail = @order.order_details.find_by(id: @order_detail_id)
        respond_to do |format|
            if @order_detail.update_attributes(order_params)
                format.html { redirect_to carts_path, notice: 'Cart Updated.' }
            else
                format.html { render :edit } 
            end
        end
        @order.save!
    end

    def destroy
        @order = current_order
        @order_detail_id = params[:id].to_i
        @order_detail = @order.order_details.find_by(id: @order_detail_id)
        @order_detail.destroy
        respond_to do |format|
            format.html { redirect_to carts_path, notice: 'Item was removed from the cart.' }
        end
        @order.save!
    end

    private def order_params
        params.require(:order_detail).permit(:product_id, :quantity)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    def show
        #render plain: current_order.inspect
        @order = Order.find_by(id: session[:order_id])
        @order_details = @order.order_details
        if @order.status == 'pending'
            @title = 'Your Current Order Details'
        elsif @order.status == 'placed'
            @title = 'Your order has been placed!'
        else
            @title = 'Your order was delivered'
        end
    end

    def update_cart_status
        @order = Order.find_by(id: session[:order_id])
        @order.status = 1
        @order.user.is_cart_empty = true
        @order.save!
        @order.user.save!
        #current_order = Order.new()
        respond_to do |format|
            format.html { redirect_to orders_path }
        end
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    before_action :set_product, only: [:show, :edit, :update, :destroy]
    
    def index
        @products = Product.all
        @order_details = current_order.order_details.new
    end
  
    def create
        @products = Product.new(product_params)
        respond_to do |format| 
            if @products.save 
                format.html { redirect_to @product, notice: 'Product was successfully created.' } 
            else 
                format.html { render :new } 
            end 
        end
    end

    private def product_params
        params.require(:product).permit(:name, :price, :description, :in_stock, :product_category_id)
    end

    def new
        @products = Product.new()
    end
  
    def edit
    end
  
    def show
        @products = Product.find(params[:id])
    end

    def set_product
        @products = Product.find(params[:id])
    end
  
    def update
        respond_to do |format|
            if @products.update(product_params)
                format.html { redirect_to @products, notice: 'Product was successfully updated.' }
            else
                format.html { render :edit } 
            end
        end
    end
  
    def destroy
        @products.in_stock = false
        @products.save!
        respond_to do |format|
            format.html { redirect_to products_path, notice: 'Product status changed to out of stock.' }
        end
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
    def current_order
        if !session[:order_id].nil? && !Order.find_by(id: session[:order_id], status: 0).nil?
            Order.find(session[:order_id])
        elsif current_user!=nil && !current_user.is_cart_empty
            Order.find_by(user_id: current_user.id, status: 0)
        else
            Order.new()
        end
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/order_details_helper.rb
module OrderDetailsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/carts/_cart.html.erb
<%= link_to "Cart #{current_order.order_details.size}", carts_path, class: 'ui blue button'%>

app/views/carts/show.html.erb
<br>
<br>
<br>
<% @order_details.each do |item| %>
    <p><%= item.product.name %></p>
    <p><%= item.product.price %></p>

    <%=  form_for item do |form| %>
        <%= form.hidden_field :product_id, :value => item.product.id %>
        <%= form.number_field :quantity, :value => item.quantity.to_i, :min => 1 %>
        <%= form.submit "update quantity", class: 'ui blue button' %>
    <% end %>
    <%= link_to 'Remove', item, method: :delete, data: {confirm: 'Are you sure?'}, class: 'ui blue button'%>
    <br>
    <b>Subtotal: <%= item.sub_total %></b>
    <br>
    <br>
<% end %>
<b><%= @body %></b>
<h3>Total:  <%= "#{current_order.total_amount}" %></h3>
<% if current_order.order_details.size > 0 %>
    <%= link_to 'Checkout', orders_path,  class: 'ui blue button'%>
<% end %>
<%= link_to 'Continue Shopping', products_path, class: 'ui blue button'%>

app/views/homes/index.html.erb
<h1>This would be my home screen</h1>

<% if current_user %>
    <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'ui blue button' %>
<% else %>
    <%= link_to 'Sign Up', new_user_registration_path, class: 'ui blue button'%>
    <%= link_to 'Sign In', new_user_session_path, class: 'ui blue button' %>
<% end %>

<%=link_to 'View Products', products_path, class: 'ui blue button'%>

app/views/layouts/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/_login_information.html.erb
<% if current_user %>
<h3>Signed in as: <%= current_user.first_name %> <%= current_user.last_name %></h3>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EComm</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/login_information' %>
    <%= render 'layouts/alerts' %>
    <%= yield %>
  </body>
</html>

app/views/order_details/create.js.erb
$('#cart').html("<%= escape_javascript(render('carts/cart')) %>")

app/views/orders/show.html.erb
<h1><%= @title %></h1>
<b>Order Details:</b>
<% @order_details.each do |item| %>
    <p><b>Name: </b><%= item.product.name %></p>
    <p><b>Price: </b><%= item.product.price %></p>
    <p><b>Quantity: </b><%= item.quantity %></p>
    <p><b>Subtotal: </b><%= item.sub_total %></p>
    <br>
    <br>
<% end %>
<b>Total: <%= @order.total_amount %> </b>
<br>
<br>
<% if @order.status == 'pending' %>
    <%= link_to  'Place Order', button_path, method: :post, class: 'ui blue button'  %>
<% end %>
<% if @order.status != 'placed' %>
    <%= link_to 'Cancel', carts_path, class: 'ui blue button' %>
<% end %>
<% if @order.status == 'placed' %>
    <%= link_to 'Continue Shopping', products_path, class: 'ui blue button' %>
<% end %>

app/views/products/_product_form.html.erb
<div class="ui form" style= "width:50%">
    <div class="field">
        <%= form_for(products) do |form| %>
            <div class="sixteen wide fields">
                <p class= "inline field">
                    <%= form.label :Name %>
                    <%= form.text_field :name %>
                </p>
                <p class= "inline field">
                    <%= form.label :Price %>
                    <%=form.number_field :price, step: :any %>
                </p>
            </div>
            <div class="fifteen wide field">
            <p>
                <%= form.label :Description %>
                <%= form.text_area :description %>
                <!--category-->
            </p>
            </div>  
            <div class="fifteen wide fields">
            <p class= "inline field">
                <%= form.label :"is in stock" %>
                <%= form.check_box :in_stock %>
            </p>
            <p class= "inline field">
                <%= form.label :"Categories:" %>
            </p>
                <%= form.select :product_category_id, options_for_select(ProductCategory.all.map{|p|[p.name, p.id]}) %>
            </div>
            <p class= "field">
                <%=link_to 'Back', products_path, class: 'ui blue button'%>
                <%= form.submit 'Submit', :class => 'ui blue button' %>
            </p>
        <% end %>
    </div>
</div>

app/views/products/edit.html.erb
<h1>Edit this product </h1> 
<%= render :partial => 'product_form', locals: {products: @products} %>

app/views/products/index.html.erb
<h1>This is product index page</h1>
<% if current_user && current_user.is_admin %>
<%= link_to 'Add Product', new_product_path, class: 'ui blue button'%>
<% end %>
<%=link_to 'Home', root_path, class: 'ui blue button'%>
<% if current_user %>
<div id="cart" style= "float:right">
    <%= render 'carts/cart'%>
</div>
<% end %>
<h2>Products</h2>
<table id="Product List" class="ui celled table" style="width:100%">
        <thead>
            <tr>
                <th>Name</th>
                <th>Price</th>
                <th>Available</th>
                <th>Description</th>
                <th>Know More</th>
                <% if current_user %>
                    <th>Buy</th>
                <% end %>
                <% if current_user && current_user.is_admin %>
                    <th>Edit</th>
                    <th>Delete</th>   
                <% end %>         
            </tr>
        </thead>
        <tbody>
            <%@products.each do |product|%>
            <tr>
                <td><%=product.name%></td>
                <td><%=product.price%></td>
                <td>
                    <%=product.in_stock ? "YES" : "NO" %>
                </td>
                <td><%=product.description%></td>
                <td><%= link_to 'View More', product, class: 'ui blue button'%></td>
                <% if current_user %>
                    <td>
                        <%= form_for @order_details, remote: true do |add| %>
                            <%= add.hidden_field :product_id, :value => product.id %>
                            <% if product.in_stock %>
                                <%= add.number_field :quantity, :value => 1, :min => 1 %>
                                <%= add.submit 'Add To Cart', class: 'ui blue button' %>
                            <% else %>
                                <p>Currently Unavailable</p>
                            <% end %>
                        <% end %>
                    </td>
                <% end %>
                <% if current_user && current_user.is_admin %>
                    <td><%= link_to 'Edit', edit_product_path(product.id), class: 'ui blue button'%></td>
                    <td><%= link_to 'Delete', product, method: :delete, data: {confirm: 'Are you sure?'}, class: 'ui blue button'%></td>
                <% end %>
            </tr>
            <%end%>
        </tbody>
</table>

app/views/products/new.html.erb
<h1>Add Product</h1>
<%= render :partial => 'product_form', locals: {products: @products} %>

app/views/products/show.html.erb
<h1>Product Details</h1>
<table id="Product List" class="ui celled table" style="width:70%">
        <tbody>
            <tr></tr>
                <tr>
                    <td>Name</td>
                    <td><%=@products.name%></td>
                </tr>
                <tr>
                    <td>Price</td>
                    <td><%=@products.price%></td>
                </tr>
                <tr>
                    <td>Availibility</td>
                    <td><%=@products.in_stock ? "YES" : "NO" %></td>
                </tr>
                <tr>
                    <td>Category</td>
                    <td></td>
                </tr>
                <tr>
                    <td>Description</td>
                    <td><%=@products.description%></td>
                </tr>
        </tbody>
</table>
<br>
<%=link_to 'back', products_path, class: 'ui blue button'%>